app = "keywords-p12-api"
primary_region = "gru"

[build]
  dockerfile = "backend/Dockerfile"

[http_service]
  internal_port = 8011
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
